In [1]:
x = [1,2,3,4]

In [3]:
out = []

for num in x:
    out.append(num**2)

In [4]:
print(out)

[1, 4, 9, 16]


In [6]:
[num**2 for num in x]

[1, 4, 9, 16]

In [10]:
def jams(p1):
    print('hello ' + p1)

In [8]:
jams(yo)

NameError: name 'yo' is not defined

In [12]:
jams('yo')

hello yo


In [13]:
jams

<function __main__.jams(p1)>

In [17]:
def sq(num):
    """
    this allows for big long doc strings
    spread over lots of lines in the code
    """
    return num**2

In [16]:
sq(23432)


549058624

In [18]:
sq

<function __main__.sq(num)>

In [19]:
seq = [1,2,3,4,5]

In [26]:
list(map(lambda num: num**40, seq))

[1,
 1099511627776,
 12157665459056928801,
 1208925819614629174706176,
 9094947017729282379150390625]

In [28]:
list(filter(lambda num: num%2 == 0, seq))

[2, 4]

In [29]:
s = "i'm sick of lying bitches"

In [32]:
s.split()

["i'm", 'sick', 'of', 'lying', 'bitches']

In [36]:
tweet = 'Go Sports! #Sports #Balls #things and other things'

In [38]:
tweet.split('#')[1]

'Sports '

In [41]:
d = {'d1':'foo','d2':'bar'}

In [42]:
d

{'d1': 'foo', 'd2': 'bar'}

In [44]:
d.keys()

dict_keys(['d1', 'd2'])

In [45]:
d.items()

dict_items([('d1', 'foo'), ('d2', 'bar')])

In [47]:
d.values()

dict_values(['foo', 'bar'])

In [48]:
list = [1,2,3]

In [49]:
list.pop()

3

In [50]:
list

[1, 2]

In [51]:
list.append('new')

### 'x' in list

In [54]:
x = [(1,2),(3,4),(5,6)]

In [56]:
x[0][1]

2

In [58]:
for (a,b) in x:
    print(a)

1
3
5


In [61]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print(arr)

[1 2 3]


In [154]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [144]:
arr = np.arange(0,11)

In [150]:
arr[0]

0

In [153]:
arr[0:5] = 100


In [145]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [72]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
np.linspace(0,100,40)

array([  0.        ,   2.56410256,   5.12820513,   7.69230769,
        10.25641026,  12.82051282,  15.38461538,  17.94871795,
        20.51282051,  23.07692308,  25.64102564,  28.20512821,
        30.76923077,  33.33333333,  35.8974359 ,  38.46153846,
        41.02564103,  43.58974359,  46.15384615,  48.71794872,
        51.28205128,  53.84615385,  56.41025641,  58.97435897,
        61.53846154,  64.1025641 ,  66.66666667,  69.23076923,
        71.79487179,  74.35897436,  76.92307692,  79.48717949,
        82.05128205,  84.61538462,  87.17948718,  89.74358974,
        92.30769231,  94.87179487,  97.43589744, 100.        ])

In [77]:
np.eye(14)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [79]:
np.random.rand(5,5)

array([[0.49866521, 0.43734573, 0.40980632, 0.40057115, 0.55001472],
       [0.83719664, 0.40344652, 0.1264357 , 0.73547774, 0.03916311],
       [0.17248048, 0.32487505, 0.21012688, 0.05875386, 0.99763002],
       [0.45757527, 0.21126718, 0.77478058, 0.38969957, 0.14209039],
       [0.35408854, 0.22566524, 0.88496053, 0.06630126, 0.41320252]])

In [127]:
arr = np.arange(25)

In [128]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [129]:
ranarr = np.random.randint(0,50,10)

In [130]:
ranarr

array([41,  4, 14,  0, 43, 16, 36, 48,  4,  1])

In [137]:
arr = arr.reshape(5,5)

In [134]:
ranarr.argmin()

3

In [138]:
arr.shape

(5, 5)

In [139]:
arr.dtype

dtype('int64')

In [157]:
arr_2d = np.arange(0,11)

In [158]:
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))


In [171]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [170]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [172]:
arr = np.arange(1,11)

In [174]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [191]:
bool_arr = arr > 5

In [177]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [197]:
arr_2d = np.arange(50).reshape(5,10)

In [198]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [201]:
len(arr[arr % 2 == 1])

5

In [205]:
dd

NameError: name 'dd' is not defined

In [206]:
dsfdf

NameError: name 'dsfdf' is not defined

In [207]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [210]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])